all:
	# g++ -o main -L /usr/local/cuda-6.5/lib64 `pkg-config opencv --cflags` main.cpp `pkg-config opencv --libs` -std=c++11 
	g++ -o testing -L /usr/local/cuda-6.5/lib64 `pkg-config opencv --cflags` testing.cpp `pkg-config opencv --libs` -std=c++11 
